### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/gabrielamartinezch-HTML5-form#1]
# Revisión - Necesita correcciones :warning:
- [ ] Estilo de código y limpieza
# Feedback
-  @gabrielamartinezch hay algunas cosas que tienes que corregir de tu código para poder darlo por aprobado
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- 
![Captura de pantalla de 2024-03-14 11-54-15](https://github.com/4GeeksAcademy/gabrielamartinezch-HTML5-form/assets/139759297/f5ef1643-6211-4b50-abae-d5090d8b4d1a)
Tienes una serie de inputs inutilizados (en rojo) y otros con un "tick" (en verde). No están siendo funcionales.
El problema está en la las clases de bootstrap que les has dado `is-invalid` y `is-valid`

**Comment by gabrielamartinezch** [comment]
Hola, Edo:
Gracias por el feedback. 
Pensaba que era normal que aparecieran de esa manera y se quitaría solo jeje. 
He eliminado is-invalid y is-valid y ya no me salen los mensajes rojos y verdes. ¿Así estaría correcto? ¿o hay otra manera?

**Comment by EduardoHernandezGuzman** [comment]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- Muy buen trabajo solucionando los problemas del código @gabrielamartinezch ... ¡Felicidades!
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- Buen trabajo
